### ISSUE TITLE
Popup doesn't work in a shadow root

### ISSUE THREAD

**Issue by ezenkico** [Ennoriel/svelte-awesome-color-picker#45] opened 2023-07-19 13:36 UTC
The Color Picker doesn't appear when it's in a shadow root.
The isOpen class isn't set on picker.

Also, in your website, can you specify the prop settings needed to put the color picker in the always open mode.
Thanks

**Comment by Ennoriel** [comment] 2023-07-19 15:16
Thanks for using the library!

What do you mean by using the component in a shadow root? Do you have a repl or a repro repo? ;)

I'll update the doc for the open version

**Comment by ezenkico** [comment] 2023-07-19 16:43
Hi

Thanks for the quick response.

What I'm doing is creating a shadow root/shadow dom and attaching the svelte app to that.
`root = parent.attachShadow({mode: 'open'});`
`new App({target: root, props: {});`
See https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM

This allows you to isolate css but will also block you from using document.query on any of the html elements.

If you could help me out I'd appreciate it.

Thanks

**Comment by Ennoriel** [comment] 2023-07-19 20:05
Thanks for your reply!

I'll be able to look at it starting next week.

**Comment by ezenkico** [comment] 2023-07-19 20:06
Awesome

**Comment by Ennoriel** [comment] 2023-07-28 05:51
Hey @ezenkico !

I understand that you are using the shadow dom to mount a svelte app but I have no idea how. Would you have a simple reproduction repo with an `index.html` (or a Svelte / React app) file importing the bundled Svelte app?

Thanks!

**Comment by Ennoriel** [comment] 2023-08-09 05:20
I am closing this as I cannot reproduce. Reopen it when you have time to give me some insights ;)

**Closed by Ennoriel** 2023-08-09 05:20 UTC
