### ISSUE TITLE
Console warning: ''[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive."

### ISSUE THREAD

**Issue by caseyplummer4haliontech** [Ennoriel/svelte-awesome-color-picker#44] opened 2023-07-09 15:31 UTC
Using Svelte 4.0.3

![image](https://github.com/Ennoriel/svelte-awesome-color-picker/assets/69089120/4d044387-37c8-46ce-b18d-5f140e24a42d)

See:
https://chromestatus.com/feature/5745543795965952

**Comment by Ennoriel** [comment] 2023-07-09 17:20
Hey,

Thanks for using the library!

Can you be a little bit more specific?

Thanks!

**Comment by Ennoriel** [comment] 2023-07-28 05:57
@caseyplummer4haliontech can you please elaborate on this issue? Which browser are you using? Where and when are you seeing this issue? I cannot reproduce on the doc site!

**Comment by Ennoriel** [comment] 2023-08-09 05:20
I am closing this as I cannot reproduce. Reopen it when you have time to give me some insights ;)

**Closed by Ennoriel** 2023-08-09 05:20 UTC

**Comment by panos-stavrianos** [comment] 2023-09-24 20:35
This is happening to me also in a clean project on Chrome Version 117.0.5938.92 (Official Build) (64-bit) (Linux), but not in Firefox.

**Comment by Ennoriel** [comment] 2024-01-08 20:25
This issue is fixed in the version 3 (still in beta)
