### ISSUE TITLE
Issues with setting color

### ISSUE THREAD

**Issue by MySpaceEmoCat** [Ennoriel/svelte-awesome-color-picker#5] opened 2022-06-15 19:02 UTC
Hello.

I'm editing the issue to indicate that the problem I had was resolved. The core of the problem seems to be the following function present in the file `convert.js`:

```
function hex2rgb(hex) {
    const h = hex.hex;
    return {
        r: parseInt(h.substring(1, 2), 16),
        g: parseInt(h.substring(3, 2), 16),
        b: parseInt(h.substring(5, 2), 16),
        a: h.length <= 7 ? 1 : parseInt(h.substring(7, 2), 16) / 255
    };
```
I appears that the `substring` method is being used incorrectly. I adjusted the function like so:

```
function hex2rgb(hex) {
    const h = hex.hex;
    return {
        r: parseInt(h.substring(1, 3), 16),
        g: parseInt(h.substring(3, 5), 16),
        b: parseInt(h.substring(5, 7), 16),
        a: h.length <= 7 ? 1 : parseInt(h.substring(7, 9), 16) / 255
    };
};
```

and that fixed all the problems I was having.

**Comment by Ennoriel** [comment] 2022-07-08 20:58
Hello @MySpaceEmoCat 

I just saw your issue yesterday! I updated the lib with this fix. I also fixed the other issue about the types and release and brand new 1.0.0 version. The API has slightly changed: instead of a color object, there are now three variables: rgb, hsv and hex.

Please let me know if it's working for you!

**Comment by MySpaceEmoCat** [comment] 2022-07-19 19:19
Sorry for the late reply! Everything seems to work fine. One more thing I forgot to mention: when `isAlpha` is set to false, it'd be nice to not include the alpha channel in the hex code, since its disabled anyway.

**Comment by Ennoriel** [comment] 2022-07-20 19:29
Hello @MySpaceEmoCat

For the alpha being added to the hexadecimal value, it's not that simple because someone could set the alpha value to 0.5 and disable changing it... So I just removed it when the alpha value was 1 (or ff in hexadecimal).

I split the color into 3 separate objects for typing reasons. I'll have to figure out how to fix it.

**Comment by MySpaceEmoCat** [comment] 2022-07-20 20:54
Thats fair, I understand.

I'm trying to wrap the color picker into another component that has inputs for the RGB and Hex, and the inner workings of the plugin don't let me change the inputs, since it always resets them right away. If that could be fixed, it'd be very nice. Let me know if you need me to provide any code or additional information.

**Comment by Ennoriel** [comment] 2022-07-21 06:11
I'll fix it!

Have a look at the [feature/input branch](https://github.com/Ennoriel/svelte-awesome-color-picker/tree/feature/input). It should have all you are looking for. But:

- it's not up to date. I'll merge the master branch in a few minutes
- it's unfinished: if you're willing to start from there to implement it and make a PR, it would be great!

**Comment by MySpaceEmoCat** [comment] 2022-07-21 08:48
Awesome, thanks! 

I'll give it a look, but I'm somewhat of a beginner with Svelte.

**Comment by Ennoriel** [comment] 2022-07-22 05:24
For the color updates from outside, it should be fixed. Let me know if you still see some cases not working ;)

For the inidividual color format input, i'll try to do something!

**Comment by MySpaceEmoCat** [comment] 2022-07-22 11:30
Everything seems to work perfectly, thank you! The input issue was fixed as well, since it also depended on the same fix.

**Comment by Ennoriel** [comment] 2022-07-22 12:27
I released a version 1.2.0 with inputs included. Let me know if it's good for you ;)

**Comment by MySpaceEmoCat** [comment] 2022-07-22 12:33
They look great! RGB mode doesn't seem to feature an input for the alpha channel it seems.

**Comment by Ennoriel** [comment] 2022-07-22 17:06
I added the alpha channel for each color. You can remove the input by setting the props isTextInput to false. I also added a isDark props!

**Comment by MySpaceEmoCat** [comment] 2022-07-23 17:13
I've installed both the latest version of the color picker and chyme, and it seems like the circle on the color selection box no longer follows the mouse. I've tried changing parameters and it doesn't seem like its doing anything.

**Comment by Ennoriel** [comment] 2022-07-23 17:40
What exactly do you see? It seems that there is a few px wrong for the Chrome color picker (that I'll fix) but it's still working though.
Here is a REPL with the 3 variants: https://svelte.dev/repl/ccb9511222ec414f9c01d7254ed96692?version=3.49.0

By the way, you don't need chyme if you don't use it elsewhere ;)

**Comment by MySpaceEmoCat** [comment] 2022-07-23 17:42
I'm on Firefox, here is a GIF recording: https://imgur.com/a/ZpyQJiK

**Comment by Ennoriel** [comment] 2022-07-23 18:31
Can you reproduce on the REPL? I cannot reproduce and I am using ffx too. I'll need a bit more insight to fix this ;)

For chyme, it's my fault, I'll fix this! :)

**Comment by jrmoynihan** [comment] 2022-07-24 00:40
I noticed the chyme issue when building too.  Glad it's on the radar!

Just a quick heads-up: there's a leftover reactive statement at line 116 of the ColorPicker component in the latest release:

`$: console.log(isDark)`

**Comment by MySpaceEmoCat** [comment] 2022-07-24 06:07
I can't replicate the issue on REPL, as it seems to work fine there:https://svelte.dev/repl/641077cafee24a42abf60b486f0bea63?version=3.49.0

However, I updated the color picker on my other project and the circle doesn't move either. Also something seems to have changed in the styles: https://imgur.com/a/cxZsbS7

**Comment by Ennoriel** [comment] 2022-07-24 06:13
Both (chyme + console.log) should be fixed now with v.1.2.3.

@jrmoynihan Thanks for reporting the console.log)
@MySpaceEmoCat what svelte version are you using on your project? (the one set in package-lock or pnpm-lock.yaml) I do reproduce with svelte v. lower than 3.46.0 as I changed `style="top: {pos.y}px"` with `style:top="{top.y}px"`

**Comment by MySpaceEmoCat** [comment] 2022-07-24 06:16
The first project is v3.45.0 and the second project is v3.0.0.

**Comment by Ennoriel** [comment] 2022-07-24 06:28
I will revert these changes as some people might have a lower version too. But you can still update svelte to the [latest version](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md). 🤖

**Comment by MySpaceEmoCat** [comment] 2022-07-24 06:28
I updated to the latest version on the second project with seemingly no issues, thank you!

**Comment by Ennoriel** [comment] 2022-07-24 06:53
I updated the lib! I close this issue. If you see anything else, feel free to open a new issue 😸

**Closed by Ennoriel** 2022-07-24 06:53 UTC
